spring:
    config:
        import: security-variable.yml
    application:
        name: PersonalSns
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sns_ryu
        username: root
        password: ${mysql.password} 